server {
    listen 80;
    server_name raft-messaging.xyz;

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name raft-messaging.xyz;

    ssl_certificate     /etc/letsencrypt/live/raft-messaging.xyz/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/raft-messaging.xyz/privkey.pem;

    root /usr/share/nginx/html;
    index index.html;

    location /api/stream {
        proxy_pass http://raft-gateway:8080/stream;
        proxy_http_version 1.1;
        proxy_set_header Connection '';
        proxy_buffering off;
        proxy_cache off;
        proxy_read_timeout 24h;
    }

    location /api/ {
        proxy_pass http://raft-gateway:8080/;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
