syntax = "proto3";
option java_package = "raf.rs";
option java_multiple_files = true;

service RAFT {
  rpc ClientCommand (Command) returns (ClientMessageRes);
  rpc Stop(StopReq) returns (StopRes);
  rpc Pause(PauseReq) returns (PauseRes);
  rpc Resume(ResumeReq) returns (ResumeRes);
}
message Command {
  oneof type {
    AddCommand addCommand = 1;
  }
}
message AddCommand {
  int32  messageId = 1;
  string user      = 2;
  string message   = 3;
  string timestamp = 4;
}
message StopReq {}
message StopRes {
  string message = 1;
}
message ClientMessageRes{
  bool   success = 1;
  string info    = 2;
}
message PauseReq  {}
message PauseRes  {}
message ResumeReq {}
message ResumeRes {}