syntax = "proto3";
option java_package = "raf.rs.RPC";
option java_multiple_files = true;

service RAFT {
  rpc AppendEntries(AppendEntriesReq) returns (AppendEntriesRes);
  rpc RequestVote(RequestVoteReq) returns (RequestVoteRes);
  rpc ClientCommand (Command) returns (ClientMessageRes);
  rpc GetAllMessages (MessageRequest) returns (AllMessages);
  rpc Stop(StopReq) returns (StopRes);
  rpc Pause(PauseReq) returns (PauseRes);
  rpc Resume(ResumeReq) returns (ResumeRes);
}
message AppendEntriesReq {
  int64 term = 1;
  int64 leaderId = 2;
  int64 prevLogIndex = 3;
  int64 prevLogTerm = 4;
  repeated LogEntry entry = 5;
  int64 leaderCommit = 6;
}
message LogEntry {
  int64 index = 1;
  int64 term = 2;
  Command command = 3;
}
message Command {
  oneof type {
    AddCommand addCommand = 1;
    DeleteCommand deleteCommand = 2;
  }
}
message AddCommand {
  int32  messageId = 1;
  string user      = 2;
  string message   = 3;
  string timestamp = 4;
}
message DeleteCommand {
  int32 messageId = 1;
  string user = 2;
}
message MessageRequest {}
message AllMessages {
  repeated Message message = 1;
}
message Message {
  int32  messageId = 1;
  string user      = 2;
  string message   = 3;
  string timestamp = 4;
  bool deleted = 5;
  int32  logIndex = 6;
}
message AppendEntriesRes {
  int64 term = 1;
  bool success = 2;
}
message RequestVoteReq {
  int64 term = 1;
  int64 candidateId = 2;
  int64 lastLogIndex = 3;
  int64 lastLogTerm = 4;
}
message RequestVoteRes {
  int64 term = 1;
  bool voteGranted = 2;
}
message StopReq {}
message StopRes {
  string message = 1;
}
message ClientMessageRes{
  bool   success = 1;
  string info    = 2;
}
message PauseReq  {}
message PauseRes  {}
message ResumeReq {}
message ResumeRes {}