spring.application.name=raft-gateway
raft.cluster.host=${RAFT_CLUSTER_HOST:localhost}
raft.cluster.port=${RAFT_CLUSTER_PORT:9000}
raft.cluster.nodes=${RAFT_CLUSTER_NODES:localhost:9000,localhost:9001,localhost:9002,localhost:9003,localhost:9004}
logging.pattern.console=%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n
